name = "GeneralizedBeta1Distribution"
uuid = "3ad0a3b9-3e73-4fed-b062-3818f061ed69"
authors = ["Mattias Villani"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
